# Generated by Django 4.2.4 on 2023-08-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.TextField(blank=True)),
                ('Date', models.DateField(blank=True)),
                ('Paragraph', models.TextField(blank=True)),
                ('Paragraph2', models.TextField(blank=True)),
                ('Paragraph3', models.TextField(blank=True)),
                ('Paragraph4', models.TextField(blank=True)),
                ('Paragraph5', models.TextField(blank=True)),
                ('Paragraph6', models.TextField(blank=True)),
                ('Paragraph7', models.TextField(blank=True)),
                ('Paragraph8', models.TextField(blank=True)),
                ('Paragraph9', models.TextField(blank=True)),
                ('Paragraph10', models.TextField(blank=True)),
                ('Paragraph11', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Issue', models.CharField(max_length=280)),
                ('Date', models.DateField(blank=True)),
                ('One_Detail', models.CharField(blank=True, max_length=280)),
                ('Second_Detail', models.CharField(blank=True, max_length=280)),
                ('Third_Detail', models.CharField(blank=True, max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=280)),
                ('HyperLink', models.CharField(max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('One', models.TextField(blank=True)),
                ('Two', models.TextField(blank=True)),
                ('Date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
