# Generated by Django 4.2.4 on 2023-08-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='Date',
            field=models.DateField(blank=True, default='2023-08-18'),
            preserve_default=False,
        ),

    ]
