# Generated by Django 4.2.4 on 2023-08-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0002_alter_issue_one_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='Date',
            field=models.DateField(blank=True, default='2023-08-17'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='Second_Detail',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='issue',
            name='Third_Detail',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
