# Generated by Django 4.1.6 on 2023-02-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Password",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(blank=True, max_length=255)),
                ("Password", models.CharField(blank=True, max_length=255)),
                ("TOTP", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
