# Generated by Django 4.1.6 on 2023-02-07 23:31

from django.db import migrations, models
import password.validators


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="password",
            name="Atachment",
            field=models.FileField(
                default="jkasdflajsdf",
                upload_to="",
                validators=[password.validators.validate_file_size],
            ),
        ),
        migrations.AddField(
            model_name="password",
            name="Date_Created",
            field=models.DateField(default='2022-02-01'),
        ),
    ]
