# Generated by Django 4.1.6 on 2023-02-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0003_alter_password_date_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(blank=True, max_length=255)),
                ("Website", models.CharField(blank=True, max_length=255)),
                ("Key_ID", models.CharField(blank=True, max_length=255)),
                ("Secret_key", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
