# Generated by Django 4.1.6 on 2023-02-08 19:20

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0004_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="password",
            name="Password",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
