# Generated by Django 4.1.6 on 2023-02-09 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("password", "0005_alter_password_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Encryption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        default=b"oAwMvhnZMSQ23Wgtoy2NRb2EOL2rqsg_7ZMK1qdzr5g="
                    ),
                ),
                (
                    "Owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
