# Generated by Django 4.1.6 on 2023-02-09 16:30

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("password", "0008_alter_encryption_key_alter_password_totp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryption",
            name="Key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                default=b"EFKEjgDhHRYcsJPeOJGHIxYwVhQXqWgHqewswi8RF6A="
            ),
        ),
    ]
