# Generated by Django 4.1.6 on 2023-02-09 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("password", "0010_remove_encryption_id_alter_encryption_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryption",
            name="Key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                default=b"vCkH_U5FYe7i6C-E9Lzk7b2MQrhElzoYXQNInB16r2g="
            ),
        ),
        migrations.AlterField(
            model_name="encryption",
            name="Owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
