# Generated by Django 4.2.4 on 2024-01-05 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lisence", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegDevice",
            fields=[
                ("key", models.CharField(max_length=255)),
                (
                    "Serial",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LinkedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Key", models.CharField(max_length=255)),
                (
                    "Device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lisence.regdevice",
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
