# Generated by Django 4.2.4 on 2024-01-08 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lisence", "0002_regdevice_linkeduser"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcessRequest",
            fields=[
                (
                    "code",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("key", models.CharField(max_length=255)),
                ("premisions", models.CharField(max_length=1024)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="linkeduser",
            name="premisions",
            field=models.CharField(default="NONE", max_length=1024),
        ),
        migrations.CreateModel(
            name="ConfCode",
            fields=[
                (
                    "code",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "req",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lisence.acessrequest",
                    ),
                ),
            ],
        ),
    ]
