# Generated by Django 4.2.4 on 2024-01-02 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_ID',
            fields=[
                ('Key_lookup', models.BigIntegerField(blank=True, default=82452555)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Encryption',
            fields=[
                ('Owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Owner_ID', models.BigIntegerField(blank=True, default=82452355)),
                ('Salt', models.CharField(default='0', max_length=500)),
                ('IV', models.CharField(default='0', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PWcheck',
            fields=[
                ('Owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Owner_ID', models.BigIntegerField(blank=True, default=82452355)),
                ('Test_PW', models.CharField(blank=True, max_length=500)),
                ('Answer', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('Name', models.CharField(blank=True, max_length=255)),
                ('Website', models.CharField(blank=True, max_length=255)),
                ('Id', models.IntegerField(blank=True, default='0000', editable=False, primary_key=True, serialize=False)),
                ('Secret_key', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=255)),
                ('Password', models.CharField(blank=True, max_length=255)),
                ('URL', models.URLField(blank=True, default='google.com')),
                ('TOTP', models.CharField(blank=True, max_length=255)),
                ('Date_Created', models.DateField(default=django.utils.timezone.now)),
                ('Notes', models.CharField(blank=True, default='this is blank', max_length=500)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
