# Generated by Django 4.1.6 on 2023-02-09 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import pwmanager.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Encryption",
            fields=[
                (
                    "Owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "Key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        default=b"9OylVsckQcVC2Fs6cGBSljarMPK4oHjxS8DkVKIeu4Y="
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Password",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(blank=True, max_length=255)),
                (
                    "Password",
                    encrypted_model_fields.fields.EncryptedCharField(blank=True),
                ),
                ("TOTP", encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                (
                    "Atachment",
                    models.FileField(
                        default="jkasdflajsdf",
                        upload_to="",
                        validators=[pwmanager.validators.validate_file_size],
                    ),
                ),
                ("Date_Created", models.DateField(default="2023-02-01")),
            ],
        ),
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(blank=True, max_length=255)),
                ("Website", models.CharField(blank=True, max_length=255)),
                ("Key_ID", models.CharField(blank=True, max_length=255)),
                ("Secret_key", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
