# Generated by Django 4.1.6 on 2023-02-09 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pwmanager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="password",
            name="Owner",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="encryption",
            name="Key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                default=b"1QsPjb1TmyV1o3yGOqdLdA1CE08Gz3A3d102_25R8C0="
            ),
        ),
        migrations.AlterField(
            model_name="encryption",
            name="Owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
