# Generated by Django 4.1.6 on 2023-02-10 15:11

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pwmanager", "0002_password_owner_alter_encryption_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryption",
            name="Id",
            field=models.IntegerField(blank=True, default="0000", max_length=16),
        ),
        migrations.AddField(
            model_name="password",
            name="Id",
            field=models.IntegerField(blank=True, default="0000", max_length=16),
        ),
        migrations.AlterField(
            model_name="encryption",
            name="Key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                default=b"2bsSv9gLhdzZ3ffMYTdFaL2RmEQlV2PXTVjLAOqxTrQ="
            ),
        ),
    ]
