# Generated by Django 4.1.6 on 2023-02-10 15:11

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pwmanager", "0003_encryption_id_password_id_alter_encryption_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryption",
            name="Id",
            field=models.IntegerField(blank=True, default="0000"),
        ),
        migrations.AlterField(
            model_name="encryption",
            name="Key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                default=b"vTWtN6I-vnWNmdI0BzAztZVqhoGrDsAzk0q7C4ezj3I="
            ),
        ),
        migrations.AlterField(
            model_name="password",
            name="Id",
            field=models.IntegerField(blank=True, default="0000"),
        ),
    ]
