# Generated by Django 4.1.6 on 2023-02-12 14:59

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pwmanager", "0004_alter_encryption_id_alter_encryption_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryption",
            name="Key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                default=b"Ffsx2A5029BT2zGak6dWLone-g99wfPpSY6Js301WxA="
            ),
        ),
    ]
