# Generated by Django 4.1.6 on 2023-02-12 15:39

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pwmanager", "0006_alter_encryption_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryption",
            name="Key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                default=b"L4pw7i5PvrZgoQ0wcFwBhhLr_ifdMIYWRYoWeCUTlEw="
            ),
        ),
    ]
