# Generated by Django 4.1.6 on 2023-02-12 15:41

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pwmanager", "0007_alter_encryption_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryption",
            name="Key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                default=b"hIEh3tG6NOJTMaC62WK6hvID2cm5H1DObUISJeK8hBw="
            ),
        ),
    ]
