# Generated by Django 4.1.6 on 2023-02-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwmanager', '0008_alter_encryption_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryption',
            name='Key',
        ),
        migrations.AddField(
            model_name='encryption',
            name='Salt',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='password',
            name='Password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='password',
            name='TOTP',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
