# Generated by Django 4.2.4 on 2023-08-03 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pwmanager", "0012_remove_encryption_id_remove_password_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="password",
            name="Date_Created",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 3, 14, 55, 10, 477390, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
