# Generated by Django 4.2.4 on 2023-08-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pwmanager", "0013_alter_password_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="password",
            name="Date_Created",
            field=models.DateField(default="django.utils.timezone.now"),
        ),
    ]
