# Generated by Django 4.2.4 on 2023-08-03 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pwmanager.validators


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pwmanager", "0014_alter_password_date_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="PW",
            fields=[
                ("Username", models.CharField(blank=True, max_length=255)),
                ("Password", models.CharField(blank=True, max_length=255)),
                ("URL", models.URLField(blank=True, default="google.com")),
                ("TOTP", models.CharField(blank=True, max_length=255)),
                (
                    "Atachment",
                    models.FileField(
                        default="jkasdflajsdf",
                        upload_to="",
                        validators=[pwmanager.validators.validate_file_size],
                    ),
                ),
                ("Date_Created", models.DateField(default="django.utils.timezone.now")),
                (
                    "ID",
                    models.IntegerField(
                        blank=True,
                        default="0000",
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "Note",
                    models.CharField(
                        blank=True, default="this is blank", max_length=500
                    ),
                ),
                (
                    "Owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Password",
        ),
        migrations.AddField(
            model_name="encryption",
            name="ID",
            field=models.IntegerField(
                blank=True,
                default="0000",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="encryption",
            name="Owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
