# Generated by Django 4.2.4 on 2023-08-03 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pwmanager", "0015_pw_delete_password_encryption_owner_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryption",
            name="Owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
