# Generated by Django 4.2.4 on 2023-08-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pwmanager", "0016_alter_encryption_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pw",
            old_name="Note",
            new_name="Notes",
        ),
        migrations.RemoveField(
            model_name="pw",
            name="ID",
        ),
        migrations.AddField(
            model_name="pw",
            name="Owner_ID",
            field=models.IntegerField(blank=True, default="0000", editable=False),
        ),
        migrations.AddField(
            model_name="pw",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                #default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
