# Generated by Django 4.2.4 on 2023-08-03 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pwmanager", "0017_rename_note_pw_notes_remove_pw_id_pw_owner_id_pw_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data_ID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Key_lookup",
                    models.IntegerField(blank=True, default=824523555, editable=False),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
