# Generated by Django 4.2.4 on 2023-08-03 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pwmanager", "0019_remove_data_id_id_alter_data_id_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data_id",
            name="User",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
