# Generated by Django 4.2.4 on 2023-08-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pwmanager", "0020_alter_data_id_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data_id",
            name="Key_lookup",
            field=models.IntegerField(blank=True, default=82452555, editable=False),
        ),
        migrations.AlterField(
            model_name="encryption",
            name="Owner_ID",
            field=models.IntegerField(blank=True, default=82452355, editable=False),
        ),
    ]
