# Generated by Django 4.2.4 on 2023-08-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pwmanager", "0021_alter_data_id_key_lookup_alter_encryption_owner_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data_id",
            name="Key_lookup",
            field=models.BigIntegerField(blank=True, default=82452555),
        ),
        migrations.AlterField(
            model_name="encryption",
            name="Owner_ID",
            field=models.BigIntegerField(blank=True, default=82452355),
        ),
    ]
