# Generated by Django 4.2.4 on 2023-08-19 13:15

from django.db import migrations, models
import pwmanager.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pwmanager', '0022_alter_data_id_key_lookup_alter_encryption_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pw',
            name='Atachment',
            field=models.FileField(blank=True, default='jkasdflajsdf', upload_to='', validators=[pwmanager.validators.validate_file_size]),
        ),
    ]
