# Generated by Django 4.2.4 on 2023-08-20 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pwmanager', '0023_alter_pw_atachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pw',
            name='Owner_ID',
        ),
        migrations.AlterField(
            model_name='pw',
            name='Date_Created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
