# Generated by Django 4.2.4 on 2023-08-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwmanager', '0024_remove_pw_owner_id_alter_pw_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pw',
            name='TOTP',
            field=models.CharField(blank=True, default='N/A', max_length=255),
        ),
    ]
