# Generated by Django 4.2.4 on 2023-09-02 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwmanager', '0026_pwcheck_encryption_iv_alter_pw_totp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pw',
            name='Atachment',
        ),
    ]
