# Generated by Django 4.2.4 on 2024-01-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Devsesion",
            fields=[
                (
                    "User",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("Password", models.CharField(max_length=255)),
            ],
        ),
    ]
