# Generated by Django 4.2.4 on 2023-11-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="Salt",
        ),
        migrations.AddField(
            model_name="device",
            name="Pub_key",
            field=models.CharField(default="10000", max_length=1024),
        ),
    ]
