# Generated by Django 4.2.4 on 2023-11-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_remove_device_cookie_id_remove_device_device_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='UID',
            field=models.CharField(default='munchy', max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='Pub_key',
            field=models.CharField(default='10000', max_length=1024),
        ),
    ]
